<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[methodName:= unitTests.ReportTest.listenerTest;status:=INFO;message:=This is info]]>
    </line>
    <line>
      <![CDATA[methodName:= unitTests.ReportTest.listenerTest2;status:=PASS;message:=This is info]]>
    </line>
    <line>
      <![CDATA[methodName:= unitTests.ReportTest.listenerTest3;status:=FAIL;message:=This is info]]>
    </line>
  </reporter-output>
  <suite started-at="2022-01-07T20:55:22 IST" name="Suite1" finished-at="2022-01-07T20:55:22 IST" duration-ms="67">
    <groups>
    </groups>
    <test started-at="2022-01-07T20:55:22 IST" name="DummyTest" finished-at="2022-01-07T20:55:22 IST" duration-ms="67">
      <class name="unitTests.ReportTest">
        <test-method signature="listenerTest()[pri:0, instance:unitTests.ReportTest@131774fe]" started-at="2022-01-07T20:55:22 IST" name="listenerTest" finished-at="2022-01-07T20:55:22 IST" duration-ms="24" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[methodName:= unitTests.ReportTest.listenerTest;status:=INFO;message:=This is info]]>
            </line>
          </reporter-output>
        </test-method> <!-- listenerTest -->
        <test-method signature="listenerTest2()[pri:0, instance:unitTests.ReportTest@131774fe]" started-at="2022-01-07T20:55:22 IST" name="listenerTest2" finished-at="2022-01-07T20:55:22 IST" duration-ms="4" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[methodName:= unitTests.ReportTest.listenerTest2;status:=PASS;message:=This is info]]>
            </line>
          </reporter-output>
        </test-method> <!-- listenerTest2 -->
        <test-method signature="listenerTest3()[pri:0, instance:unitTests.ReportTest@131774fe]" started-at="2022-01-07T20:55:22 IST" name="listenerTest3" finished-at="2022-01-07T20:55:22 IST" duration-ms="2" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at org.testng.Assert.assertFalse(Assert.java:77)
at unitTests.ReportTest.listenerTest3(unitTests.ReportTest.java:23)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[methodName:= unitTests.ReportTest.listenerTest3;status:=FAIL;message:=This is info]]>
            </line>
          </reporter-output>
        </test-method> <!-- listenerTest3 -->
      </class> <!-- unitTests.ReportTest -->
    </test> <!-- DummyTest -->
  </suite> <!-- Suite1 -->
</testng-results>
